language: node_js
node_js:
  - "4.6.1"
  - "5.12.0"
  - "6.9.1"
  - "7.0.0"
env:
  - EXPORT_COVERAGE=1 CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
branches:
  only:
    - master
